server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:9296
  security:
    basic:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://abhi:3306/spyneUserService
    username: abhi
    password: abhi
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Uncomment the following line to enable SQL logging
  # jpa.show-sql: true


